framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    # Forces the internal table to live inside your schema
                    table_name: 'classycash.messenger_messages'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - messenger.middleware.router_context
                    - messenger.middleware.doctrine_close_connection
                    - messenger.middleware.doctrine_transaction
                    - messenger.middleware.validation

        routing:
            'Symfony\Component\Notifier\Message\MessageInterface': sync
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync
            'App\Application\Command\SaveTransfer': sync
            'App\Application\Command\MatchPaymentForTransfer': sync
            'App\Application\Command\Notification\NewUser': sync
            'App\Application\Command\Notification\SendSettlementConfirmationEmail': sync
            'App\Application\Command\Notification\TransferNotMatchedCommand': sync
            'App\Application\Command\RecalculateCashState': async
            'App\Application\Command\RecalculateAllCashState': sync
            '*': async

when@test:
    framework:
        messenger:
            transports:
                async: test://
            routing:
                'App\Application\Command\SaveTransfer': async
                'App\Application\Command\MatchPaymentForTransfer': async
                'App\Application\Command\Notification\NewUser': async
                'App\Application\Command\Notification\SendSettlementConfirmationEmail': async
                'App\Application\Command\Notification\TransferNotMatchedCommand': async
                'App\Application\Command\RecalculateCashState': async
                'App\Application\Command\RecalculateAllCashState': async
                'Symfony\Component\Notifier\Message\MessageInterface': async
                'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
                '*': async

