symfony_health_check:
    health_error_response_code: 503
    ping_error_response_code: 503
    health_checks:
        - id: symfony_health_check.environment_check
        - id: symfony_health_check.status_up_check
        - id: symfony_health_check.doctrine_orm_check
        - id: SwooleBundle\Observability\HealthCheck\HttpClientHealthCheck
        - id: SwooleBundle\Observability\HealthCheck\ProcessCountHealthCheck
        - id: SwooleBundle\Observability\HealthCheck\MemoryUsageHealthCheck
        - id: SwooleBundle\Scheduler\HealthCheck\SchedulerHeartbeatHealthCheck
    ping_checks:
        - id: symfony_health_check.status_up_check
