---
# Classy-Cash Deployment Configuration
apps:
  - name: classy-cash
    domain: skarbiec.mleczki.pl
    port: 9501
    image: ghcr.io/mleczakm/classy-cash:{{ app_version | default('latest') }}
    env:
      APP_ENV: prod
      APP_VERSION: "{{ app_version | default('latest') }}"
    healthcheck_enabled: true
    ipv6: "{{ mikrus_ipv6 }}"
    cytrus_host: "{{ cytrus_host }}"
    proxied: true
