---
- name: Deploy Classy-Cash Application
  hosts: mikrus
  become: yes
  vars_files:
    - config.yml
  tasks:
    - name: Deploy classy-cash app
      include_role:
        name: app_deploy
      loop: "{{ apps }}"
      loop_control:
        loop_var: app
